### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by AlexNek** [elmahio-blog/PopperBlazor#1]
I have a lot of curious errors: VS 2019 Community, Win 10
1>xxx\Src\PopperBlazor-main\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(1,1,1,1):
error CS1056: Unexpected character 'xxx\Src\PopperBlazor-main\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(1,2,1,2): error CS1056: Unexpected character 'xxx\Src\PopperBlazor-main\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(1,3,1,3): 
....
\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(1,189,1,189): error CS1056: Unexpected character xxx\Src\PopperBlazor-main\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(1,190,1,190): error CS1056: Unexpected character 'Done building project "PopperBlazor.csproj" -- FAILED.

**Comment by ThomasArdal** [comment]
Not sure this works with newer versions of .NET. Closing for now, since this is just a repo for hosting the code for the blog post. Thanks.
